name: flutter_ine_service
description: Servicio Flutter independiente para procesamiento de credenciales INE mexicanas, diseñado para integración con React Native.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Dependencias para procesamiento de imágenes
  image: ^4.1.3
  path: ^1.8.3
  
  # Dependencias para detección y procesamiento
  google_mlkit_text_recognition: ^0.11.0
  google_mlkit_face_detection: ^0.10.0
  
  # Dependencias para códigos QR y barras
  qr_code_scanner: ^1.0.1
  
  # Utilidades
  path_provider: ^2.1.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: mx.d3c.dev.flutter_ine_service
        pluginClass: FlutterIneServicePlugin
  
  assets:
    - assets/
    - assets/roi_templates/
    - assets/roi_templates/config/