name: ine_processor_module
description: Módulo Flutter para procesamiento de credenciales INE integrable con React Native
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_barcode_scanning: ^0.14.1
  
  # Image processing
  image: ^4.1.3
  camera: ^0.11.2
  
  # File handling
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Utilities
  intl: ^0.20.2
  crypto: ^3.0.3
  
  # JSON serialization
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.12

# Configuración específica para módulo
flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.atom.ine_processor
    iosBundleIdentifier: com.atom.ineProcessor